### PR TITLE
Event listening

### PR DESCRIPTION
**Pull request by yasserf**

### CODE REVIEW

**Comment by yasserf** [comment]
@WolframHempel

**Comment by jwanglof** [comment]
Isn't this already implemented in `client.event.subscribe( 'news/politics', function( news ), callback)`?

**Comment by yasserf** [comment]
@jwanglof This is to mimic the record.listen functionality.

It's mainly for 'providers' ( any client that publishes data ) to allow them to only emit data only when at least one client is interested.

so its:
```javascript
client.event.listen( 'news/*', function( subject, subscribed ) {
    if( subscribed ) {
       // start emitting relevant events;
    } else {
       // stop emitting relevant events;
   }
} )
```

**Comment by jwanglof** [comment]
Ah, very nice!

**Pull request merged**
